name: Node.js CI

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Xvfb
      run: sudo apt-get install -y xvfb
    - name: Start Xvfb
      run: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    - run: npm ci
    - run: npm run lint
    - name: Run tests with Xvfb
      run: |
        export DISPLAY=:99
        npm test